# Generated by Django 5.2.14 on 2026-05-14 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=200)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "loyalty_points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customer",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="customer_full_na_4f1b36_idx"
                    ),
                    models.Index(fields=["phone"], name="customer_phone_ea919e_idx"),
                    models.Index(fields=["email"], name="customer_email_c21aac_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earn"),
                            ("redeem", "Redeem"),
                            ("adjust", "Adjust"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_transaction",
                "ordering": ["-created_at"],
            },
        ),
    ]
